/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE RADIO PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Status generated by radio.
 */
public class msg_radio extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_RADIO = 166;
    public static final int MAVLINK_MSG_LENGTH = 9;
    private static final long serialVersionUID = MAVLINK_MSG_ID_RADIO;

    
    /**
     * Receive errors.
     */
    @Description("Receive errors.")
    @Units("")
    public int rxerrors;
    
    /**
     * Count of error corrected packets.
     */
    @Description("Count of error corrected packets.")
    @Units("")
    public int fixed;
    
    /**
     * Local signal strength.
     */
    @Description("Local signal strength.")
    @Units("")
    public short rssi;
    
    /**
     * Remote signal strength.
     */
    @Description("Remote signal strength.")
    @Units("")
    public short remrssi;
    
    /**
     * How full the tx buffer is.
     */
    @Description("How full the tx buffer is.")
    @Units("%")
    public short txbuf;
    
    /**
     * Background noise level.
     */
    @Description("Background noise level.")
    @Units("")
    public short noise;
    
    /**
     * Remote background noise level.
     */
    @Description("Remote background noise level.")
    @Units("")
    public short remnoise;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_RADIO;

        packet.payload.putUnsignedShort(rxerrors);
        packet.payload.putUnsignedShort(fixed);
        packet.payload.putUnsignedByte(rssi);
        packet.payload.putUnsignedByte(remrssi);
        packet.payload.putUnsignedByte(txbuf);
        packet.payload.putUnsignedByte(noise);
        packet.payload.putUnsignedByte(remnoise);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a radio message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.rxerrors = payload.getUnsignedShort();
        this.fixed = payload.getUnsignedShort();
        this.rssi = payload.getUnsignedByte();
        this.remrssi = payload.getUnsignedByte();
        this.txbuf = payload.getUnsignedByte();
        this.noise = payload.getUnsignedByte();
        this.remnoise = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_radio() {
        this.msgid = MAVLINK_MSG_ID_RADIO;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_radio( int rxerrors, int fixed, short rssi, short remrssi, short txbuf, short noise, short remnoise) {
        this.msgid = MAVLINK_MSG_ID_RADIO;

        this.rxerrors = rxerrors;
        this.fixed = fixed;
        this.rssi = rssi;
        this.remrssi = remrssi;
        this.txbuf = txbuf;
        this.noise = noise;
        this.remnoise = remnoise;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_radio( int rxerrors, int fixed, short rssi, short remrssi, short txbuf, short noise, short remnoise, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_RADIO;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.rxerrors = rxerrors;
        this.fixed = fixed;
        this.rssi = rssi;
        this.remrssi = remrssi;
        this.txbuf = txbuf;
        this.noise = noise;
        this.remnoise = remnoise;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_radio(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_RADIO;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                  
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_RADIO - sysid:"+sysid+" compid:"+compid+" rxerrors:"+rxerrors+" fixed:"+fixed+" rssi:"+rssi+" remrssi:"+remrssi+" txbuf:"+txbuf+" noise:"+noise+" remnoise:"+remnoise+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_RADIO";
    }
}
        