/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MOUNT_CONFIGURE PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Message to configure a camera mount, directional antenna, etc.
 */
public class msg_mount_configure extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MOUNT_CONFIGURE = 156;
    public static final int MAVLINK_MSG_LENGTH = 6;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MOUNT_CONFIGURE;

    
    /**
     * System ID.
     */
    @Description("System ID.")
    @Units("")
    public short target_system;
    
    /**
     * Component ID.
     */
    @Description("Component ID.")
    @Units("")
    public short target_component;
    
    /**
     * Mount operating mode.
     */
    @Description("Mount operating mode.")
    @Units("")
    public short mount_mode;
    
    /**
     * (1 = yes, 0 = no).
     */
    @Description("(1 = yes, 0 = no).")
    @Units("")
    public short stab_roll;
    
    /**
     * (1 = yes, 0 = no).
     */
    @Description("(1 = yes, 0 = no).")
    @Units("")
    public short stab_pitch;
    
    /**
     * (1 = yes, 0 = no).
     */
    @Description("(1 = yes, 0 = no).")
    @Units("")
    public short stab_yaw;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_MOUNT_CONFIGURE;

        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        packet.payload.putUnsignedByte(mount_mode);
        packet.payload.putUnsignedByte(stab_roll);
        packet.payload.putUnsignedByte(stab_pitch);
        packet.payload.putUnsignedByte(stab_yaw);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a mount_configure message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        this.mount_mode = payload.getUnsignedByte();
        this.stab_roll = payload.getUnsignedByte();
        this.stab_pitch = payload.getUnsignedByte();
        this.stab_yaw = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_mount_configure() {
        this.msgid = MAVLINK_MSG_ID_MOUNT_CONFIGURE;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_mount_configure( short target_system, short target_component, short mount_mode, short stab_roll, short stab_pitch, short stab_yaw) {
        this.msgid = MAVLINK_MSG_ID_MOUNT_CONFIGURE;

        this.target_system = target_system;
        this.target_component = target_component;
        this.mount_mode = mount_mode;
        this.stab_roll = stab_roll;
        this.stab_pitch = stab_pitch;
        this.stab_yaw = stab_yaw;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_mount_configure( short target_system, short target_component, short mount_mode, short stab_roll, short stab_pitch, short stab_yaw, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_MOUNT_CONFIGURE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.target_system = target_system;
        this.target_component = target_component;
        this.mount_mode = mount_mode;
        this.stab_roll = stab_roll;
        this.stab_pitch = stab_pitch;
        this.stab_yaw = stab_yaw;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_mount_configure(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_MOUNT_CONFIGURE;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_MOUNT_CONFIGURE - sysid:"+sysid+" compid:"+compid+" target_system:"+target_system+" target_component:"+target_component+" mount_mode:"+mount_mode+" stab_roll:"+stab_roll+" stab_pitch:"+stab_pitch+" stab_yaw:"+stab_yaw+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_MOUNT_CONFIGURE";
    }
}
        