/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Actuator output function. Values greater or equal to 1000 are autopilot-specific.
 */
public class ACTUATOR_OUTPUT_FUNCTION {
   public static final int ACTUATOR_OUTPUT_FUNCTION_NONE = 0; /* No function (disabled). | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR1 = 1; /* Motor 1 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR2 = 2; /* Motor 2 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR3 = 3; /* Motor 3 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR4 = 4; /* Motor 4 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR5 = 5; /* Motor 5 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR6 = 6; /* Motor 6 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR7 = 7; /* Motor 7 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR8 = 8; /* Motor 8 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR9 = 9; /* Motor 9 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR10 = 10; /* Motor 10 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR11 = 11; /* Motor 11 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR12 = 12; /* Motor 12 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR13 = 13; /* Motor 13 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR14 = 14; /* Motor 14 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR15 = 15; /* Motor 15 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_MOTOR16 = 16; /* Motor 16 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO1 = 33; /* Servo 1 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO2 = 34; /* Servo 2 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO3 = 35; /* Servo 3 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO4 = 36; /* Servo 4 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO5 = 37; /* Servo 5 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO6 = 38; /* Servo 6 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO7 = 39; /* Servo 7 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO8 = 40; /* Servo 8 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO9 = 41; /* Servo 9 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO10 = 42; /* Servo 10 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO11 = 43; /* Servo 11 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO12 = 44; /* Servo 12 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO13 = 45; /* Servo 13 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO14 = 46; /* Servo 14 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO15 = 47; /* Servo 15 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_SERVO16 = 48; /* Servo 16 | */
   public static final int ACTUATOR_OUTPUT_FUNCTION_ENUM_END = 49; /*  | */
}
            