/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Type of AIS vessel, enum duplicated from AIS standard, https://gpsd.gitlab.io/gpsd/AIVDM.html
*/
public class AIS_TYPE {
   public static final int AIS_TYPE_UNKNOWN = 0; /* Not available (default). | */
   public static final int AIS_TYPE_RESERVED_1 = 1; /*  | */
   public static final int AIS_TYPE_RESERVED_2 = 2; /*  | */
   public static final int AIS_TYPE_RESERVED_3 = 3; /*  | */
   public static final int AIS_TYPE_RESERVED_4 = 4; /*  | */
   public static final int AIS_TYPE_RESERVED_5 = 5; /*  | */
   public static final int AIS_TYPE_RESERVED_6 = 6; /*  | */
   public static final int AIS_TYPE_RESERVED_7 = 7; /*  | */
   public static final int AIS_TYPE_RESERVED_8 = 8; /*  | */
   public static final int AIS_TYPE_RESERVED_9 = 9; /*  | */
   public static final int AIS_TYPE_RESERVED_10 = 10; /*  | */
   public static final int AIS_TYPE_RESERVED_11 = 11; /*  | */
   public static final int AIS_TYPE_RESERVED_12 = 12; /*  | */
   public static final int AIS_TYPE_RESERVED_13 = 13; /*  | */
   public static final int AIS_TYPE_RESERVED_14 = 14; /*  | */
   public static final int AIS_TYPE_RESERVED_15 = 15; /*  | */
   public static final int AIS_TYPE_RESERVED_16 = 16; /*  | */
   public static final int AIS_TYPE_RESERVED_17 = 17; /*  | */
   public static final int AIS_TYPE_RESERVED_18 = 18; /*  | */
   public static final int AIS_TYPE_RESERVED_19 = 19; /*  | */
   public static final int AIS_TYPE_WIG = 20; /* Wing In Ground effect. | */
   public static final int AIS_TYPE_WIG_HAZARDOUS_A = 21; /*  | */
   public static final int AIS_TYPE_WIG_HAZARDOUS_B = 22; /*  | */
   public static final int AIS_TYPE_WIG_HAZARDOUS_C = 23; /*  | */
   public static final int AIS_TYPE_WIG_HAZARDOUS_D = 24; /*  | */
   public static final int AIS_TYPE_WIG_RESERVED_1 = 25; /*  | */
   public static final int AIS_TYPE_WIG_RESERVED_2 = 26; /*  | */
   public static final int AIS_TYPE_WIG_RESERVED_3 = 27; /*  | */
   public static final int AIS_TYPE_WIG_RESERVED_4 = 28; /*  | */
   public static final int AIS_TYPE_WIG_RESERVED_5 = 29; /*  | */
   public static final int AIS_TYPE_FISHING = 30; /*  | */
   public static final int AIS_TYPE_TOWING = 31; /*  | */
   public static final int AIS_TYPE_TOWING_LARGE = 32; /* Towing: length exceeds 200m or breadth exceeds 25m. | */
   public static final int AIS_TYPE_DREDGING = 33; /* Dredging or other underwater ops. | */
   public static final int AIS_TYPE_DIVING = 34; /*  | */
   public static final int AIS_TYPE_MILITARY = 35; /*  | */
   public static final int AIS_TYPE_SAILING = 36; /*  | */
   public static final int AIS_TYPE_PLEASURE = 37; /*  | */
   public static final int AIS_TYPE_RESERVED_20 = 38; /*  | */
   public static final int AIS_TYPE_RESERVED_21 = 39; /*  | */
   public static final int AIS_TYPE_HSC = 40; /* High Speed Craft. | */
   public static final int AIS_TYPE_HSC_HAZARDOUS_A = 41; /*  | */
   public static final int AIS_TYPE_HSC_HAZARDOUS_B = 42; /*  | */
   public static final int AIS_TYPE_HSC_HAZARDOUS_C = 43; /*  | */
   public static final int AIS_TYPE_HSC_HAZARDOUS_D = 44; /*  | */
   public static final int AIS_TYPE_HSC_RESERVED_1 = 45; /*  | */
   public static final int AIS_TYPE_HSC_RESERVED_2 = 46; /*  | */
   public static final int AIS_TYPE_HSC_RESERVED_3 = 47; /*  | */
   public static final int AIS_TYPE_HSC_RESERVED_4 = 48; /*  | */
   public static final int AIS_TYPE_HSC_UNKNOWN = 49; /*  | */
   public static final int AIS_TYPE_PILOT = 50; /*  | */
   public static final int AIS_TYPE_SAR = 51; /* Search And Rescue vessel. | */
   public static final int AIS_TYPE_TUG = 52; /*  | */
   public static final int AIS_TYPE_PORT_TENDER = 53; /*  | */
   public static final int AIS_TYPE_ANTI_POLLUTION = 54; /* Anti-pollution equipment. | */
   public static final int AIS_TYPE_LAW_ENFORCEMENT = 55; /*  | */
   public static final int AIS_TYPE_SPARE_LOCAL_1 = 56; /*  | */
   public static final int AIS_TYPE_SPARE_LOCAL_2 = 57; /*  | */
   public static final int AIS_TYPE_MEDICAL_TRANSPORT = 58; /*  | */
   public static final int AIS_TYPE_NONECOMBATANT = 59; /* Noncombatant ship according to RR Resolution No. 18. | */
   public static final int AIS_TYPE_PASSENGER = 60; /*  | */
   public static final int AIS_TYPE_PASSENGER_HAZARDOUS_A = 61; /*  | */
   public static final int AIS_TYPE_PASSENGER_HAZARDOUS_B = 62; /*  | */
   public static final int AIS_TYPE_AIS_TYPE_PASSENGER_HAZARDOUS_C = 63; /*  | */
   public static final int AIS_TYPE_PASSENGER_HAZARDOUS_D = 64; /*  | */
   public static final int AIS_TYPE_PASSENGER_RESERVED_1 = 65; /*  | */
   public static final int AIS_TYPE_PASSENGER_RESERVED_2 = 66; /*  | */
   public static final int AIS_TYPE_PASSENGER_RESERVED_3 = 67; /*  | */
   public static final int AIS_TYPE_AIS_TYPE_PASSENGER_RESERVED_4 = 68; /*  | */
   public static final int AIS_TYPE_PASSENGER_UNKNOWN = 69; /*  | */
   public static final int AIS_TYPE_CARGO = 70; /*  | */
   public static final int AIS_TYPE_CARGO_HAZARDOUS_A = 71; /*  | */
   public static final int AIS_TYPE_CARGO_HAZARDOUS_B = 72; /*  | */
   public static final int AIS_TYPE_CARGO_HAZARDOUS_C = 73; /*  | */
   public static final int AIS_TYPE_CARGO_HAZARDOUS_D = 74; /*  | */
   public static final int AIS_TYPE_CARGO_RESERVED_1 = 75; /*  | */
   public static final int AIS_TYPE_CARGO_RESERVED_2 = 76; /*  | */
   public static final int AIS_TYPE_CARGO_RESERVED_3 = 77; /*  | */
   public static final int AIS_TYPE_CARGO_RESERVED_4 = 78; /*  | */
   public static final int AIS_TYPE_CARGO_UNKNOWN = 79; /*  | */
   public static final int AIS_TYPE_TANKER = 80; /*  | */
   public static final int AIS_TYPE_TANKER_HAZARDOUS_A = 81; /*  | */
   public static final int AIS_TYPE_TANKER_HAZARDOUS_B = 82; /*  | */
   public static final int AIS_TYPE_TANKER_HAZARDOUS_C = 83; /*  | */
   public static final int AIS_TYPE_TANKER_HAZARDOUS_D = 84; /*  | */
   public static final int AIS_TYPE_TANKER_RESERVED_1 = 85; /*  | */
   public static final int AIS_TYPE_TANKER_RESERVED_2 = 86; /*  | */
   public static final int AIS_TYPE_TANKER_RESERVED_3 = 87; /*  | */
   public static final int AIS_TYPE_TANKER_RESERVED_4 = 88; /*  | */
   public static final int AIS_TYPE_TANKER_UNKNOWN = 89; /*  | */
   public static final int AIS_TYPE_OTHER = 90; /*  | */
   public static final int AIS_TYPE_OTHER_HAZARDOUS_A = 91; /*  | */
   public static final int AIS_TYPE_OTHER_HAZARDOUS_B = 92; /*  | */
   public static final int AIS_TYPE_OTHER_HAZARDOUS_C = 93; /*  | */
   public static final int AIS_TYPE_OTHER_HAZARDOUS_D = 94; /*  | */
   public static final int AIS_TYPE_OTHER_RESERVED_1 = 95; /*  | */
   public static final int AIS_TYPE_OTHER_RESERVED_2 = 96; /*  | */
   public static final int AIS_TYPE_OTHER_RESERVED_3 = 97; /*  | */
   public static final int AIS_TYPE_OTHER_RESERVED_4 = 98; /*  | */
   public static final int AIS_TYPE_OTHER_UNKNOWN = 99; /*  | */
   public static final int AIS_TYPE_ENUM_END = 100; /*  | */
}
            