/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Camera Modes.
*/
public class CAMERA_MODE {
   public static final int CAMERA_MODE_IMAGE = 0; /* Camera is in image/photo capture mode. | */
   public static final int CAMERA_MODE_VIDEO = 1; /* Camera is in video capture mode. | */
   public static final int CAMERA_MODE_IMAGE_SURVEY = 2; /* Camera is in image survey capture mode. It allows for camera controller to do specific settings for surveys. | */
   public static final int CAMERA_MODE_ENUM_END = 3; /*  | */
}
            