/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Type of landing target
*/
public class LANDING_TARGET_TYPE {
   public static final int LANDING_TARGET_TYPE_LIGHT_BEACON = 0; /* Landing target signaled by light beacon (ex: IR-LOCK) | */
   public static final int LANDING_TARGET_TYPE_RADIO_BEACON = 1; /* Landing target signaled by radio beacon (ex: ILS, NDB) | */
   public static final int LANDING_TARGET_TYPE_VISION_FIDUCIAL = 2; /* Landing target represented by a fiducial marker (ex: ARTag) | */
   public static final int LANDING_TARGET_TYPE_VISION_OTHER = 3; /* Landing target represented by a pre-defined visual shape/feature (ex: X-marker, H-marker, square) | */
   public static final int LANDING_TARGET_TYPE_ENUM_END = 4; /*  | */
}
            