/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Winch status flags used in WINCH_STATUS
 */
public class MAV_WINCH_STATUS_FLAG {
   public static final int MAV_WINCH_STATUS_HEALTHY = 1; /* Winch is healthy | */
   public static final int MAV_WINCH_STATUS_FULLY_RETRACTED = 2; /* Winch line is fully retracted | */
   public static final int MAV_WINCH_STATUS_MOVING = 4; /* Winch motor is moving | */
   public static final int MAV_WINCH_STATUS_CLUTCH_ENGAGED = 8; /* Winch clutch is engaged allowing motor to move freely. | */
   public static final int MAV_WINCH_STATUS_LOCKED = 16; /* Winch is locked by locking mechanism. | */
   public static final int MAV_WINCH_STATUS_DROPPING = 32; /* Winch is gravity dropping payload. | */
   public static final int MAV_WINCH_STATUS_ARRESTING = 64; /* Winch is arresting payload descent. | */
   public static final int MAV_WINCH_STATUS_GROUND_SENSE = 128; /* Winch is using torque measurements to sense the ground. | */
   public static final int MAV_WINCH_STATUS_RETRACTING = 256; /* Winch is returning to the fully retracted position. | */
   public static final int MAV_WINCH_STATUS_REDELIVER = 512; /* Winch is redelivering the payload. This is a failover state if the line tension goes above a threshold during RETRACTING. | */
   public static final int MAV_WINCH_STATUS_ABANDON_LINE = 1024; /* Winch is abandoning the line and possibly payload. Winch unspools the entire calculated line length. This is a failover state from REDELIVER if the number of attempts exceeds a threshold. | */
   public static final int MAV_WINCH_STATUS_LOCKING = 2048; /* Winch is engaging the locking mechanism. | */
   public static final int MAV_WINCH_STATUS_LOAD_LINE = 4096; /* Winch is spooling on line. | */
   public static final int MAV_WINCH_STATUS_LOAD_PAYLOAD = 8192; /* Winch is loading a payload. | */
   public static final int MAV_WINCH_STATUS_FLAG_ENUM_END = 8193; /*  | */
}
            