/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class MAV_ODID_DESC_TYPE {
   public static final int MAV_ODID_DESC_TYPE_TEXT = 0; /* Free-form text description of the purpose of the flight. | */
   public static final int MAV_ODID_DESC_TYPE_ENUM_END = 1; /*  | */
}
            