/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class MAV_ODID_OPERATOR_LOCATION_TYPE {
   public static final int MAV_ODID_OPERATOR_LOCATION_TYPE_TAKEOFF = 0; /* The location/altitude of the operator is the same as the take-off location. | */
   public static final int MAV_ODID_OPERATOR_LOCATION_TYPE_LIVE_GNSS = 1; /* The location/altitude of the operator is dynamic. E.g. based on live GNSS data. | */
   public static final int MAV_ODID_OPERATOR_LOCATION_TYPE_FIXED = 2; /* The location/altitude of the operator are fixed values. | */
   public static final int MAV_ODID_OPERATOR_LOCATION_TYPE_ENUM_END = 3; /*  | */
}
            