/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class MAV_ODID_OPERATOR_ID_TYPE {
   public static final int MAV_ODID_OPERATOR_ID_TYPE_CAA = 0; /* CAA (Civil Aviation Authority) registered operator ID. | */
   public static final int MAV_ODID_OPERATOR_ID_TYPE_ENUM_END = 1; /*  | */
}
            