/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Smart battery supply status/fault flags (bitmask) for health indication. The battery must also report either MAV_BATTERY_CHARGE_STATE_FAILED or MAV_BATTERY_CHARGE_STATE_UNHEALTHY if any of these are set.
 */
public class MAV_BATTERY_FAULT {
   public static final int MAV_BATTERY_FAULT_DEEP_DISCHARGE = 1; /* Battery has deep discharged. | */
   public static final int MAV_BATTERY_FAULT_SPIKES = 2; /* Voltage spikes. | */
   public static final int MAV_BATTERY_FAULT_CELL_FAIL = 4; /* One or more cells have failed. Battery should also report MAV_BATTERY_CHARGE_STATE_FAILE (and should not be used). | */
   public static final int MAV_BATTERY_FAULT_OVER_CURRENT = 8; /* Over-current fault. | */
   public static final int MAV_BATTERY_FAULT_OVER_TEMPERATURE = 16; /* Over-temperature fault. | */
   public static final int MAV_BATTERY_FAULT_UNDER_TEMPERATURE = 32; /* Under-temperature fault. | */
   public static final int MAV_BATTERY_FAULT_INCOMPATIBLE_VOLTAGE = 64; /* Vehicle voltage is not compatible with this battery (batteries on same power rail should have similar voltage). | */
   public static final int MAV_BATTERY_FAULT_INCOMPATIBLE_FIRMWARE = 128; /* Battery firmware is not compatible with current autopilot firmware. | */
   public static final int BATTERY_FAULT_INCOMPATIBLE_CELLS_CONFIGURATION = 256; /* Battery is not compatible due to cell configuration (e.g. 5s1p when vehicle requires 6s). | */
   public static final int MAV_BATTERY_FAULT_ENUM_END = 257; /*  | */
}
            