/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Flags for CURRENT_EVENT_SEQUENCE.
 */
public class MAV_EVENT_CURRENT_SEQUENCE_FLAGS {
   public static final int MAV_EVENT_CURRENT_SEQUENCE_FLAGS_RESET = 1; /* A sequence reset has happened (e.g. vehicle reboot). | */
   public static final int MAV_EVENT_CURRENT_SEQUENCE_FLAGS_ENUM_END = 2; /*  | */
}
            