/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class MOTOR_TEST_ORDER {
   public static final int MOTOR_TEST_ORDER_DEFAULT = 0; /* default autopilot motor test method | */
   public static final int MOTOR_TEST_ORDER_SEQUENCE = 1; /* motor numbers are specified as their index in a predefined vehicle-specific sequence | */
   public static final int MOTOR_TEST_ORDER_BOARD = 2; /* motor numbers are specified as the output as labeled on the board | */
   public static final int MOTOR_TEST_ORDER_ENUM_END = 3; /*  | */
}
            