/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Flags to indicate the type of storage.
 */
public class STORAGE_TYPE {
   public static final int STORAGE_TYPE_UNKNOWN = 0; /* Storage type is not known. | */
   public static final int STORAGE_TYPE_USB_STICK = 1; /* Storage type is USB device. | */
   public static final int STORAGE_TYPE_SD = 2; /* Storage type is SD card. | */
   public static final int STORAGE_TYPE_MICROSD = 3; /* Storage type is microSD card. | */
   public static final int STORAGE_TYPE_CF = 4; /* Storage type is CFast. | */
   public static final int STORAGE_TYPE_CFE = 5; /* Storage type is CFexpress. | */
   public static final int STORAGE_TYPE_XQD = 6; /* Storage type is XQD. | */
   public static final int STORAGE_TYPE_HD = 7; /* Storage type is HD mass storage type. | */
   public static final int STORAGE_TYPE_OTHER = 254; /* Storage type is other, not listed type. | */
   public static final int STORAGE_TYPE_ENUM_END = 255; /*  | */
}
            