/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMPONENT_INFORMATION PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Information about a component. For camera components instead use CAMERA_INFORMATION, and for autopilots use AUTOPILOT_VERSION. Components including GCSes should consider supporting requests of this message via MAV_CMD_REQUEST_MESSAGE.
*/
public class msg_component_information extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_COMPONENT_INFORMATION = 395;
    public static final int MAVLINK_MSG_LENGTH = 222;
    private static final long serialVersionUID = MAVLINK_MSG_ID_COMPONENT_INFORMATION;


      
    /**
    * Timestamp (time since system boot).
    */
    public long time_boot_ms;
      
    /**
    * Version of the component firmware (v << 24 & 0xff = Dev, v << 16 & 0xff = Patch, v << 8 & 0xff = Minor, v & 0xff = Major)
    */
    public long firmware_version;
      
    /**
    * Version of the component hardware (v << 24 & 0xff = Dev, v << 16 & 0xff = Patch, v << 8 & 0xff = Minor, v & 0xff = Major)
    */
    public long hardware_version;
      
    /**
    * Bitmap of component capability flags.
    */
    public long capability_flags;
      
    /**
    * Component definition version (iteration)
    */
    public int component_definition_version;
      
    /**
    * Name of the component vendor
    */
    public short vendor_name[] = new short[32];
      
    /**
    * Name of the component model
    */
    public short model_name[] = new short[32];
      
    /**
    * Component definition URI (if any, otherwise only basic functions will be available). The XML format is not yet specified and work in progress. 
    */
    public byte component_definition_uri[] = new byte[140];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_COMPONENT_INFORMATION;
              
        packet.payload.putUnsignedInt(time_boot_ms);
              
        packet.payload.putUnsignedInt(firmware_version);
              
        packet.payload.putUnsignedInt(hardware_version);
              
        packet.payload.putUnsignedInt(capability_flags);
              
        packet.payload.putUnsignedShort(component_definition_version);
              
        
        for (int i = 0; i < vendor_name.length; i++) {
            packet.payload.putUnsignedByte(vendor_name[i]);
        }
                    
              
        
        for (int i = 0; i < model_name.length; i++) {
            packet.payload.putUnsignedByte(model_name[i]);
        }
                    
              
        
        for (int i = 0; i < component_definition_uri.length; i++) {
            packet.payload.putByte(component_definition_uri[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a component_information message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time_boot_ms = payload.getUnsignedInt();
              
        this.firmware_version = payload.getUnsignedInt();
              
        this.hardware_version = payload.getUnsignedInt();
              
        this.capability_flags = payload.getUnsignedInt();
              
        this.component_definition_version = payload.getUnsignedShort();
              
         
        for (int i = 0; i < this.vendor_name.length; i++) {
            this.vendor_name[i] = payload.getUnsignedByte();
        }
                
              
         
        for (int i = 0; i < this.model_name.length; i++) {
            this.model_name[i] = payload.getUnsignedByte();
        }
                
              
         
        for (int i = 0; i < this.component_definition_uri.length; i++) {
            this.component_definition_uri[i] = payload.getByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_component_information(){
        msgid = MAVLINK_MSG_ID_COMPONENT_INFORMATION;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_component_information(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_COMPONENT_INFORMATION;
        unpack(mavLinkPacket.payload);        
    }

                   
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setComponent_Definition_Uri(String str) {
        int len = Math.min(str.length(), 140);
        for (int i=0; i<len; i++) {
            component_definition_uri[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<140; i++) {            // padding for the rest of the buffer
            component_definition_uri[i] = 0;
        }
    }

    /**
    * Gets the message, formated as a string
    */
    public String getComponent_Definition_Uri() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 140; i++) {
            if (component_definition_uri[i] != 0)
                buf.append((char) component_definition_uri[i]);
            else
                break;
        }
        return buf.toString();

    }
                         
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_COMPONENT_INFORMATION - sysid:"+sysid+" compid:"+compid+" time_boot_ms:"+time_boot_ms+" firmware_version:"+firmware_version+" hardware_version:"+hardware_version+" capability_flags:"+capability_flags+" component_definition_version:"+component_definition_version+" vendor_name:"+vendor_name+" model_name:"+model_name+" component_definition_uri:"+component_definition_uri+"";
    }
}
        