/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TIME_ESTIMATE_TO_TARGET PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Time/duration estimates for various events and actions given the current vehicle state and position.
 */
public class msg_time_estimate_to_target extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET = 380;
    public static final int MAVLINK_MSG_LENGTH = 20;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET;

    
    /**
     * Estimated time to complete the vehicle's configured 'safe return' action from its current position (e.g. RTL, Smart RTL, etc.). -1 indicates that the vehicle is landed, or that no time estimate available.
     */
    @Description("Estimated time to complete the vehicle's configured 'safe return' action from its current position (e.g. RTL, Smart RTL, etc.). -1 indicates that the vehicle is landed, or that no time estimate available.")
    @Units("s")
    public int safe_return;
    
    /**
     * Estimated time for vehicle to complete the LAND action from its current position. -1 indicates that the vehicle is landed, or that no time estimate available.
     */
    @Description("Estimated time for vehicle to complete the LAND action from its current position. -1 indicates that the vehicle is landed, or that no time estimate available.")
    @Units("s")
    public int land;
    
    /**
     * Estimated time for reaching/completing the currently active mission item. -1 means no time estimate available.
     */
    @Description("Estimated time for reaching/completing the currently active mission item. -1 means no time estimate available.")
    @Units("s")
    public int mission_next_item;
    
    /**
     * Estimated time for completing the current mission. -1 means no mission active and/or no estimate available.
     */
    @Description("Estimated time for completing the current mission. -1 means no mission active and/or no estimate available.")
    @Units("s")
    public int mission_end;
    
    /**
     * Estimated time for completing the current commanded action (i.e. Go To, Takeoff, Land, etc.). -1 means no action active and/or no estimate available.
     */
    @Description("Estimated time for completing the current commanded action (i.e. Go To, Takeoff, Land, etc.). -1 means no action active and/or no estimate available.")
    @Units("s")
    public int commanded_action;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET;

        packet.payload.putInt(safe_return);
        packet.payload.putInt(land);
        packet.payload.putInt(mission_next_item);
        packet.payload.putInt(mission_end);
        packet.payload.putInt(commanded_action);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a time_estimate_to_target message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.safe_return = payload.getInt();
        this.land = payload.getInt();
        this.mission_next_item = payload.getInt();
        this.mission_end = payload.getInt();
        this.commanded_action = payload.getInt();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_time_estimate_to_target() {
        this.msgid = MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_time_estimate_to_target( int safe_return, int land, int mission_next_item, int mission_end, int commanded_action) {
        this.msgid = MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET;

        this.safe_return = safe_return;
        this.land = land;
        this.mission_next_item = mission_next_item;
        this.mission_end = mission_end;
        this.commanded_action = commanded_action;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_time_estimate_to_target( int safe_return, int land, int mission_next_item, int mission_end, int commanded_action, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.safe_return = safe_return;
        this.land = land;
        this.mission_next_item = mission_next_item;
        this.mission_end = mission_end;
        this.commanded_action = commanded_action;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_time_estimate_to_target(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET - sysid:"+sysid+" compid:"+compid+" safe_return:"+safe_return+" land:"+land+" mission_next_item:"+mission_next_item+" mission_end:"+mission_end+" commanded_action:"+commanded_action+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET";
    }
}
        